### ISSUE TITLE
Shapeshifter Web App - 404 Error

### ISSUE THREAD

**Issue by stevdza-san** [alexjlockwood/ShapeShifter#341] opened 2019-12-21 08:42 UTC
What's going on?

http://prntscr.com/qdvzo7

**Comment by MrPostHipster** [comment] 2019-12-21 23:13
@stevdza-san Site is down for me as well. Pulled down a local copy, which took a bit of work to get running due to running node 13 and updated dependencies.  In short I had to:
- update angular dependencies
- lock typescript to 3.1.6 (did not want to undertake updating angular 7→8)
- specify tinycolor namespace in ColorUtil.ts
- swap Jquery.event for Jquery.TriggeredEvent in clipboard.service.ts
- update svggo dependency to package fs module with it (very much a hack, but was quickest path to getting up and running)
- polyfill global object

I can share a PR with these changes, but YMMV based on node / npm environment you have setup.

**Comment by Tsouza29** [comment] 2019-12-24 14:19
Does anyone know what happened to ShapeShifter web app?

**Comment by MihaiVoinea** [comment] 2019-12-24 14:43
Down for me as well.

I forked the repo and managed to get it working on my sub-domain, at http://shapeshifter.voinea.dev/. Feel free to use this if you need it until the issue is resolved with the official URL.

Otherwise, you can just clone the repo and run it locally.

**Comment by frist008** [comment] 2019-12-24 22:51
> Down for me as well.
> 
> I forked the repo and managed to get it working on my sub-domain, at https://shapeshifter.voinea.dev/. Feel free to use this if you need it until the issue is resolved with the official URL.
> 
> Otherwise, you can just clone the repo and run it locally.

You are my savior!

**Comment by coderofsalvation** [comment] 2020-01-02 08:58
created another backup-version here: https://coderofsalvation.gitlab.io/shapeshifter/

**Comment by alexjlockwood** [comment] 2020-01-09 02:23
Sorry about that everyone! Should be up now!

**Closed by alexjlockwood** 2020-01-09 02:23 UTC
