### ISSUE TITLE
Several SVG parsing related bugs

### ISSUE THREAD

**Issue by shiningwing** [alexjlockwood/ShapeShifter#20] opened 2017-02-21 22:20 UTC
When attempting to import SVGs (either one at a time or both at once), nothing ever appears in Shape Shifter.

Files to test:  
[arrow_back_modified.svg](https://mega.nz/#!R89k0KDL!k9gWJ_liliyQXsxQLkr1v7162fB6vqDPyCyfLiLSbs8)  
[menu.svg](https://mega.nz/#!U4lFVAgT!jePQUTNgxqhQj5tvtMZNxLp3gYsSIoG5zw6prwlLVaQ)

System info:  
Windows 10 x64 Build 14393  
Google Chrome version 56.0.2924.87 (64-bit)

**Comment by alexjlockwood** [comment] 2017-02-22 01:05
Thank you for reporting! You helped me find a couple of bugs in my SVG parser!

Out of curiosity, where did you get these SVGs from? I ask because I want to find as many SVGs that break this app as I possibly can so I can fix all of the bugs. :)

The menu SVG exposes two bugs in my code:

```
<?xml version="1.0" standalone="no"?>
<svg viewBox="0 0 24 24"
  version="1.1"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  style="width: 24px; height: 24px;">
  <path d="M3,18h18v-2H3V18z M3,13h18v-2H3V13z M3,6v2h18V6H3z" />
</svg>
```

(1) When I import this SVG, I get a type error: `Uncaught TypeError: Cannot read property 'baseVal' of undefined`. Deleting the first line seems to avoid the crash... but this is something that ShapeShifter should avoid on its own. 

(2) When I import this SVG, the fill color is not set because none is specified on the `<path>`. I should double check the SVG spec, but it would probably be best to default the fill color to `#000` if neither `stroke` or `fill` is specified.

The arrow icon exposes two bugs as well:

```
<svg xmlns:xhtml="http://www.w3.org/1999/xhtml"
  xmlns="http://www.w3.org/2000/svg"
  style="width:24px;height:24px"
  viewBox="0 0 24 24">
  <path
     d="m 20,12 -1.414214,1.414214 -8,-8.0000004 L 12,4 Z m -1,1 -15,0 0,-2 15,0 z M 20,12 12.014214,20.014214 10.6,18.6 18.585786,10.585786 Z"
     style="fill:#000000;fill-opacity:1"
     id="path5-0" />
</svg>
```

(1) My parser doesn't yet understand `<style>` attributes/tags. This is already filed at @14.

(2) It seems like there is a bug in my code that occurs when a subpath begins with a lowercase 'm'. Will have to look into that.

I was able to fix the arrow SVG by changing it to the following:

```
<svg xmlns:xhtml="http://www.w3.org/1999/xhtml"
  xmlns="http://www.w3.org/2000/svg"
  style="width:24px;height:24px"
  viewBox="0 0 24 24">
  <path d="M 20,12 l -1.414214,1.414214 -8,-8 L 12,4 Z M 19,13 l -15,0 0,-2 15,0 Z M 20,12 12.014214,20.014214 10.6,18.6 18.585786,10.585786 Z"
    fill="#000" />
</svg>
```

Thanks again for filing the bug! LMK if you encounter any other bugs. Will try to fix these for the next release.

**Comment by shiningwing** [comment] 2017-02-22 01:22
Heh, I actually got the icons years ago from an old Polymer dump, the arrow one is one I modified myself in Inkscape (saved as a plain SVG) so that it would animate how I wanted. [Here's a copy of the icons that I still have](https://mega.nz/#!VxdB1QYa!erb1DIRoRNxdLLhoyTX9_d_QPi7SjS7lFD16xtksKGk), since I still use them all the time for UI mockups. After I posted the issue, I took a look at the arrow and noticed that it had a style attribute (as per #14 as you mentioned), but after taking it out it still didn't work. Glad to see that you've figured out a way to work around it!

Thanks for looking into this! So far this is still a very awesome tool for animating icons, and I had a good time playing around with the demos trying to get them looking as good as I could get them.

**Comment by alexjlockwood** [comment] 2017-02-22 01:32
Nice! Thanks a lot for those SVGs... I've been trying to find new ones to test (parsing SVGs is hard and annoying because the spec is so huge :P).

Yeah, the arrow SVG is broken because the path starts with a lower case 'm'... right now my code doesn't handle that case (in fact, it immediately throws an [`Error`](https://github.com/alexjlockwood/ShapeShifter/blob/master/src/app/scripts/parsers/PathParser.ts#L106))... but should be easy to fix. I gotta start writing more tests... :P

**Comment by sebaslogen** [comment] 2017-02-22 14:44
I tried a couple of SVGs from wikipedia and none of them opens (tested on Win FF and Chrome):
https://upload.wikimedia.org/wikipedia/commons/8/89/Dog.svg
https://upload.wikimedia.org/wikipedia/commons/6/60/Cat_silhouette.svg

**Comment by alexjlockwood** [comment] 2017-02-22 15:58
@sebaslogen Awesome, thanks for the links! It looks like those are causing runtime exceptions as well. When I import the dog, for example, the developer console shows the error:

```
Error: Expected command
    at consumeCommand_ (http://localhost:4200/main.bundle.js:5754:19) [angular]
    at parseCommands (http://localhost:4200/main.bundle.js:5804:27) [angular]
    at Object.transformPathString (http://localhost:4200/main.bundle.js:6017:29) [angular]
    at nodeToLayerDataFn (http://localhost:4200/main.bundle.js:2211:78) [angular]
    at http://localhost:4200/main.bundle.js:2217:48 [angular]
    at Array.map (native) [angular]
    at nodeToLayerDataFn (http://localhost:4200/main.bundle.js:2217:18) [angular]
    at http://localhost:4200/main.bundle.js:2217:48 [angular]
    at Array.map (native) [angular]
    at nodeToLayerDataFn (http://localhost:4200/main.bundle.js:2217:18) [angular]
    at Object.loadVectorLayerFromSvgString (http://localhost:4200/main.bundle.js:2248:21) [angular]
    at FileReader.fileReader.onload (http://localhost:4200/main.bundle.js:3354:126) [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:56602:37) [angular]
```

SVG import/export is going to be the first thing I try to improve... starting with this weekend, most likely. Clearly I have some work to do. I gotta start writing unit tests for this stuff as well. :)

In the mean time, feel free to continue posting links to SVGs that don't work. There are so many different ways to write SVGs that it is kind of insane... the more SVGs I have to work with the more bugs I can find. :P Thanks again!

p.s. In the meantime, you might be able to avoid crashes by running your SVGs through SVGOMG before you import. SVGOMG will remove a lot of unnecessary stuff, so it would be less likely to cause problems with my current SVG parsing implementation. Here's a link: https://jakearchibald.github.io/svgomg/

**Comment by sebaslogen** [comment] 2017-02-22 16:16
I was playing some time ago with animations on this SVG and it also fails to load on FF:
https://upload.wikimedia.org/wikipedia/commons/b/be/Blendle_logo.svg

```
17:03:54.416 EXCEPTION: e.srcElement is undefined 1 vendor.56e7ee62f4367c7d411c.bundle.js:675:224
	r</t.prototype.handleError https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:675:224
	A</e.prototype._bootstrapModuleFactoryWithZone/</<.next https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:262:1757
	a</e.prototype.subscribe/i< https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:682:555
	c</e.prototype.__tryOrUnsub https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:115:3947
	c</e.prototype.next https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:115:3270
	u</e.prototype._next https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:115:2342
	u</e.prototype.next https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:115:2025
	p</e.prototype.next https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:64:3004
	a</e.prototype.emit https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:682:314
	i</t.prototype.triggerError https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:71:3317
	i</t.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onHandleError https://alexjlockwood.github.io/ShapeShifter/vendor.56e7ee62f4367c7d411c.bundle.js:71:2917
	[721]/</</x</x</t.prototype.handleError https://alexjlockwood.github.io/ShapeShifter/polyfills.3b4e34ff5fa1fbea2441.bundle.js:36:9064
	[721]/</</x</S</n.prototype.runTask https://alexjlockwood.github.io/ShapeShifter/polyfills.3b4e34ff5fa1fbea2441.bundle.js:36:5405
	t/this.invoke https://alexjlockwood.github.io/ShapeShifter/polyfills.3b4e34ff5fa1fbea2441.bundle.js:36:10539
```

Strangely enough, it loads (badly but it loads) in Chrome and selecting some of the letter paths it crashes too.


I got an idea! If you create a template test case that loads an SVG and checks the load didn't produce any exception, then we could fork that test case, create more test cases with different SVG resources and open PRs with the failing tests. This way we can also build a small regression suite 😉

**Comment by alexjlockwood** [comment] 2017-02-22 17:22
I'm open to pretty much any testing infrastructure that catches regressions. I have to admit, I don't know much about unit testing in javascript (I am still a noob at this web development stuff :P).

BTW, the exceptions you are getting are obfuscated because you are running the production version. When I run a local server I get this crash stack trace:

```
TypeError: Cannot read property 'commands' of undefined
    at LayerStateService.webpackJsonp.41.LayerStateService.replaceActivePathCommand (layerstate.service.ts:101)
    at LayerStateService.webpackJsonp.41.LayerStateService.setActivePathId (layerstate.service.ts:57)
    at PathSelectorComponent.setActivePathId (pathselector.component.ts:60)
    at View_PathSelectorComponent2.handleEvent_2 (/AppModule/PathSelectorComponent/component.ngfactory.js:84)
    at View_PathSelectorComponent2.<anonymous> (view.js:664)
    at HTMLDivElement.<anonymous> (dom_renderer.js:489)
    at ZoneDelegate.webpackJsonp.882.ZoneDelegate.invokeTask (zone.js:363)
    at Object.onInvokeTask (ng_zone.js:264)
    at ZoneDelegate.webpackJsonp.882.ZoneDelegate.invokeTask (zone.js:362)
    at Zone.webpackJsonp.882.Zone.runTask (zone.js:166)
    at HTMLDivElement.ZoneTask.invoke (zone.js:416)
```

It looks like there is a bug in `replaceActivePathCommand()` (link: https://github.com/alexjlockwood/ShapeShifter/blob/master/src/app/services/layerstate.service.ts#L90-L136) that causes the crash whenever you switch between paths with differing numbers of sub paths. Lots to fix! :)

**Comment by alexjlockwood** [comment] 2017-02-22 17:24
I think another bug related to that "Blendle" SVG is that my SVG importer currently doesn't handle fill colors set on `<group>`s and/or `<svg>` tags. I assume when that occurs, all children paths should inherit the same fill color as the parent or something like that. Will need to double check with the SVG spec.

**Comment by alexjlockwood** [comment] 2017-02-26 19:24
BTW, most of these issues I think have been fixed (or at least will be fixed once I release the new update tomorrow).

By default ShapeShifter will now run SVGO on imported SVG files, and in many cases the simplified SVGO output imports fine. :D 

Keep on reporting bugs if you find any! :)

**Comment by alexjlockwood** [comment] 2017-02-27 04:18
FYI, going to close this now because most of the issues are fixed. The only one that hasn't been fixed I believe is the one that is now tracked here: #24 

Thanks for all the help!

**Closed by alexjlockwood** 2017-02-27 04:18 UTC
Labels: bug, SVG import
